name: C++ Tests

on: [push, pull_request]

jobs:
  cpp-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ clang libgtest-dev
    - name: Configure
      run: |
        cd cpp
        mkdir build
        cd build
        cmake ..
    - name: Build
      run: |
        cd cpp/build
        make
    - name: Test
      run: |
        cd cpp/build
        ctest --output-on-failure 